
import React, { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { useGrocery } from "@/contexts/GroceryContext";
import { formatCurrency } from "@/utils/currency";

const PrintPreview = () => {
  const { id } = useParams<{ id: string }>();
  const { getListById } = useGrocery();
  const [list, setList] = useState<any>(null);

  useEffect(() => {
    if (id) {
      const groceryList = getListById(id);
      if (groceryList) {
        setList(groceryList);
      }
    }
  }, [id, getListById]);

  if (!list) {
    return <div className="p-8 text-center">List not found</div>;
  }

  return (
    <div className="p-8 max-w-4xl mx-auto">
      <style>
        {`
          @media print {
            body {
              print-color-adjust: exact;
              -webkit-print-color-adjust: exact;
            }
          }
        `}
      </style>
      
      {/* Header */}
      <div className="mb-8">
        <h1 className="text-3xl font-bold mb-2">{list.title}</h1>
        <p className="text-gray-600">
          {list.month} {list.year} • Created on {new Date(list.createdAt).toLocaleDateString()}
        </p>
        <p className="text-sm text-gray-500 mt-2">Generated by BazarBuddy</p>
      </div>
      
      {/* Items Table */}
      <table className="w-full border-collapse">
        <thead>
          <tr className="bg-orange-600 text-white">
            <th className="border border-gray-300 p-2 text-left">Item</th>
            <th className="border border-gray-300 p-2 text-left">Quantity</th>
            <th className="border border-gray-300 p-2 text-left">Unit</th>
            <th className="border border-gray-300 p-2 text-right">Est. Price (৳)</th>
          </tr>
        </thead>
        <tbody>
          {list.items.map((item: any) => (
            <tr key={item.id} className="hover:bg-gray-50">
              <td className="border border-gray-300 p-2">{item.name}</td>
              <td className="border border-gray-300 p-2">{item.quantity}</td>
              <td className="border border-gray-300 p-2">{item.unit}</td>
              <td className="border border-gray-300 p-2 text-right">
                {item.estimatedPrice ? formatCurrency(item.estimatedPrice, 'BDT') : '৳0.00'}
              </td>
            </tr>
          ))}
        </tbody>
        <tfoot>
          <tr className="bg-gray-100 font-bold">
            <td className="border border-gray-300 p-2" colSpan={3} align="right">Total:</td>
            <td className="border border-gray-300 p-2 text-right">
              {formatCurrency(list.totalEstimatedPrice, 'BDT')}
            </td>
          </tr>
        </tfoot>
      </table>
      
      {/* Footer */}
      <div className="mt-8 text-center text-gray-500 text-sm">
        <p>Printed on {new Date().toLocaleDateString()}</p>
      </div>
    </div>
  );
};

export default PrintPreview;
