// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcrwwulyhkkbuhmlzqzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indjcnd3dWx5aGtrYnVobWx6cXpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNzE3ODIsImV4cCI6MjA2MTk0Nzc4Mn0.BZRYh9hP7uw44bKEIiRFKOeoyFL0AIkThLzOfvdUmcY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);